### ISSUE TITLE
error No valid versions available for gulp-plumber

### ISSUE THREAD

**Issue by since78pl** [floatdrop/gulp-plumber#56]
I am getting this error while installing gulp-plumber (tried to clear cache):
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   '--force',
1 verbose cli   'gulp-plumber' ]
2 info using npm@5.5.1
3 info using node@v9.3.0
4 warn using --force I sure hope you know what you are doing.
5 verbose npm-session b1ebc80a75106bac
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 200 https://registry.npmjs.org/gulp-plumber 415ms
9 silly fetchPackageMetaData error for gulp-plumber@latest No valid versions available for gulp-plumber
10 verbose type tag
11 verbose stack gulp-plumber: No valid versions available for gulp-plumber
11 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:19:11)
11 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:773:18)
11 verbose stack     at tryOnImmediate (timers.js:734:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:711:5)
12 verbose cwd xxxxxxxxxx
13 verbose Linux 4.14.11-mainline-rev1
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "--force" "gulp-plumber"
15 verbose node v9.3.0
16 verbose npm  v5.5.1
17 error code ENOVERSIONS
18 error No valid versions available for gulp-plumber
19 verbose exit [ 1, true ]
```

**Comment by since78pl** [comment]
It might be related to https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by gregorskii** [comment]
Interesting timing. Me too.

**Comment by vctr90** [comment]
Same error here, I thought it was due to npm version

**Comment by gregorskii** [comment]
Seems to be back.
