### ISSUE TITLE
Converting null

### ISSUE THREAD

**Issue by xvilo** [floatdrop/gulp-plumber#57]
Hello,

When trying to install `gulp-plumber` with `nom install --save gulp-plumber` I get the following message from NPM: `Cannot convert undefined or null to object `. It seems there is somewhere a nasty bug?

My terminal output:
```
$ npm install
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xvilo/projects/customer-invoice-manager/npm-debug.log
```

Last lines of `npm-debug.log`:
```
5689 verbose addNamed ">=4.0.1 <5.0.0" is a valid semver range for object-assign
5690 silly addNameRange { name: 'object-assign',
5690 silly addNameRange   range: '>=4.0.1 <5.0.0',
5690 silly addNameRange   hasData: false }
5691 silly mapToRegistry name object-assign
5692 silly mapToRegistry using default registry
5693 silly mapToRegistry registry https://registry.npmjs.org/
5694 silly mapToRegistry data Result {
5694 silly mapToRegistry   raw: 'object-assign',
5694 silly mapToRegistry   scope: null,
5694 silly mapToRegistry   escapedName: 'object-assign',
5694 silly mapToRegistry   name: 'object-assign',
5694 silly mapToRegistry   rawSpec: '',
5694 silly mapToRegistry   spec: 'latest',
5694 silly mapToRegistry   type: 'tag' }
5695 silly mapToRegistry uri https://registry.npmjs.org/object-assign
5696 verbose addNameRange registry:https://registry.npmjs.org/object-assign not in flight; fetching
5697 verbose stack TypeError: Cannot convert undefined or null to object
5697 verbose stack     at pickVersionFromRegistryDocument (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
5697 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
5697 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
5697 verbose stack     at saved (/usr/local/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
5697 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
5697 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
5698 verbose cwd /Users/xvilo/projects/customer-invoice-manager
5699 error Darwin 17.3.0
5700 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
5701 error node v6.11.3
5702 error npm  v3.10.10
5703 error Cannot convert undefined or null to object
5704 error If you need help, you may report this error at:
5704 error     <https://github.com/npm/npm/issues>
5705 verbose exit [ 1, true ]
```

**Comment by floatdrop** [comment]
Please check https://status.npmjs.org/incidents/41zfb8qpvrdj
